name: Generate and publish Conham report

on:
  schedule:
    - cron: '15 */3 * * *'      # every hour at :15, adjust as needed
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install requests

      - name: Generate HTML report
        run: python poo.py   # replace with your filename

      - name: Commit HTML to docs/
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add docs/index.html
          git add docs/conham.html
          git add docs/chew.html
          git add docs/salford.html
          git add docs/warleigh.html
          git add docs/farleigh.html
          git add docs/index.js
          git commit -m "Update report [skip ci]" || echo "No changes to commit"

      - name: Push changes
        uses: ad-m/github-push-action@v0.8.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
